version: "3.0"

services:
  dev:
      build: .
      image: hugo:latest
      command: hugo serve --bind 0.0.0.0 --baseURL http://localhost/
      volumes:
          - .:/data
      working_dir: /data
      ports:
        - "1313:1313"
